<?php

namespace Heavymind\Oxatis\ApiClient\Services\UserServices;

use Heavymind\Oxatis\ApiClient\Type;
use Phpro\SoapClient\Soap\ClassMap\ClassMapCollection;
use Phpro\SoapClient\Soap\ClassMap\ClassMap;

class UserServicesClassmap
{

    public static function getCollection() : \Phpro\SoapClient\Soap\ClassMap\ClassMapCollection
    {
        return new ClassMapCollection([
            new ClassMap('UserAdd', Type\UserAdd::class),
            new ClassMap('WSIdentitySoap', Type\WSIdentitySoap::class),
            new ClassMap('UserEntity', Type\UserEntity::class),
            new ClassMap('UserIdEntity', Type\UserIdEntity::class),
            new ClassMap('OxatisEntity', Type\OxatisEntity::class),
            new ClassMap('CatalogAccessValueEntity', Type\CatalogAccessValueEntity::class),
            new ClassMap('TaxClassEntity', Type\TaxClassEntity::class),
            new ClassMap('CategoryEntity', Type\CategoryEntity::class),
            new ClassMap('ArrayOfCatalogAccessValueEntity', Type\ArrayOfCatalogAccessValueEntity::class),
            new ClassMap('UserAddResponse', Type\UserAddResponse::class),
            new ClassMap('SoapDataResultServiceOfOxIdDataInt32', Type\SoapDataResultServiceOfOxIdDataInt32::class),
            new ClassMap('SoapResultService', Type\SoapResultService::class),
            new ClassMap('OxIdData', Type\OxIdData::class),
            new ClassMap('UserImport', Type\UserImport::class),
            new ClassMap('UserImportResponse', Type\UserImportResponse::class),
            new ClassMap('UserUpdate', Type\UserUpdate::class),
            new ClassMap('UserUpdateResponse', Type\UserUpdateResponse::class),
            new ClassMap('UserDelete', Type\UserDelete::class),
            new ClassMap('UserDeleteResponse', Type\UserDeleteResponse::class),
            new ClassMap('UserDeleteShippingAddress', Type\UserDeleteShippingAddress::class),
            new ClassMap('UserAddressIdEntity', Type\UserAddressIdEntity::class),
            new ClassMap('UserDeleteShippingAddressResponse', Type\UserDeleteShippingAddressResponse::class),
            new ClassMap('UserUpdateBillingAddress', Type\UserUpdateBillingAddress::class),
            new ClassMap('UserUpdateBillingAddressResponse', Type\UserUpdateBillingAddressResponse::class),
            new ClassMap('UserUpdateBillingAddressLines', Type\UserUpdateBillingAddressLines::class),
            new ClassMap('UserUpdateBillingAddressLinesResponse', Type\UserUpdateBillingAddressLinesResponse::class),
            new ClassMap('UserUpdateCategories', Type\UserUpdateCategories::class),
            new ClassMap('UserUpdateCategoriesResponse', Type\UserUpdateCategoriesResponse::class),
            new ClassMap('UserUpdateCompanyName', Type\UserUpdateCompanyName::class),
            new ClassMap('UserUpdateCompanyNameResponse', Type\UserUpdateCompanyNameResponse::class),
            new ClassMap('UserUpdateCompanyVATNumber', Type\UserUpdateCompanyVATNumber::class),
            new ClassMap('UserUpdateCompanyVATNumberResponse', Type\UserUpdateCompanyVATNumberResponse::class),
            new ClassMap('UserUpdateCustomerAccount', Type\UserUpdateCustomerAccount::class),
            new ClassMap('UserUpdateCustomerAccountResponse', Type\UserUpdateCustomerAccountResponse::class),
            new ClassMap('UserUpdateEmail', Type\UserUpdateEmail::class),
            new ClassMap('UserUpdateEmailResponse', Type\UserUpdateEmailResponse::class),
            new ClassMap('UserUpdateFiscalCode', Type\UserUpdateFiscalCode::class),
            new ClassMap('UserUpdateFiscalCodeResponse', Type\UserUpdateFiscalCodeResponse::class),
            new ClassMap('UserUpdateBirthDate', Type\UserUpdateBirthDate::class),
            new ClassMap('UserUpdateBirthDateResponse', Type\UserUpdateBirthDateResponse::class),
            new ClassMap('UserUpdateFisrtName', Type\UserUpdateFisrtName::class),
            new ClassMap('UserUpdateFisrtNameResponse', Type\UserUpdateFisrtNameResponse::class),
            new ClassMap('UserUpdateLanguage', Type\UserUpdateLanguage::class),
            new ClassMap('UserUpdateLanguageResponse', Type\UserUpdateLanguageResponse::class),
            new ClassMap('UserUpdateLastName', Type\UserUpdateLastName::class),
            new ClassMap('UserUpdateLastNameResponse', Type\UserUpdateLastNameResponse::class),
            new ClassMap('UserUpdatePassword', Type\UserUpdatePassword::class),
            new ClassMap('UserUpdatePasswordResponse', Type\UserUpdatePasswordResponse::class),
            new ClassMap('UserUpdatePriceIndex', Type\UserUpdatePriceIndex::class),
            new ClassMap('UserUpdatePriceIndexResponse', Type\UserUpdatePriceIndexResponse::class),
            new ClassMap('UserUpdateDiscount', Type\UserUpdateDiscount::class),
            new ClassMap('UserUpdateDiscountResponse', Type\UserUpdateDiscountResponse::class),
            new ClassMap('UserUpdateDiscountGridCode', Type\UserUpdateDiscountGridCode::class),
            new ClassMap('UserUpdateDiscountGridCodeResponse', Type\UserUpdateDiscountGridCodeResponse::class),
            new ClassMap('UserUpdateSubscribeToNewletters', Type\UserUpdateSubscribeToNewletters::class),
            new ClassMap('UserUpdateSubscribeToNewlettersResponse', Type\UserUpdateSubscribeToNewlettersResponse::class),
            new ClassMap('UserUpdateSalesCodeRep', Type\UserUpdateSalesCodeRep::class),
            new ClassMap('UserUpdateSalesCodeRepResponse', Type\UserUpdateSalesCodeRepResponse::class),
            new ClassMap('UserUpdateShippingAddress', Type\UserUpdateShippingAddress::class),
            new ClassMap('UserUpdateShippingAddressResponse', Type\UserUpdateShippingAddressResponse::class),
            new ClassMap('UserUpdateShippingAddressLines', Type\UserUpdateShippingAddressLines::class),
            new ClassMap('UserUpdateShippingAddressLinesResponse', Type\UserUpdateShippingAddressLinesResponse::class),
            new ClassMap('UserUpdateAdditionalShippingAddress', Type\UserUpdateAdditionalShippingAddress::class),
            new ClassMap('UserShippingAddressEntity', Type\UserShippingAddressEntity::class),
            new ClassMap('UserUpdateAdditionalShippingAddressResponse', Type\UserUpdateAdditionalShippingAddressResponse::class),
            new ClassMap('UserGet', Type\UserGet::class),
            new ClassMap('UserGetResponse', Type\UserGetResponse::class),
            new ClassMap('SoapDataResultServiceOfUserDataUserEntity', Type\SoapDataResultServiceOfUserDataUserEntity::class),
            new ClassMap('UserData', Type\UserData::class),
            new ClassMap('UserGetBillingAddress', Type\UserGetBillingAddress::class),
            new ClassMap('UserGetBillingAddressResponse', Type\UserGetBillingAddressResponse::class),
            new ClassMap('UserGetBillingAddressLines', Type\UserGetBillingAddressLines::class),
            new ClassMap('UserGetBillingAddressLinesResponse', Type\UserGetBillingAddressLinesResponse::class),
            new ClassMap('UserGetCategories', Type\UserGetCategories::class),
            new ClassMap('UserGetCategoriesResponse', Type\UserGetCategoriesResponse::class),
            new ClassMap('UserGetCompanyName', Type\UserGetCompanyName::class),
            new ClassMap('UserGetCompanyNameResponse', Type\UserGetCompanyNameResponse::class),
            new ClassMap('UserGetCompanyVATNumber', Type\UserGetCompanyVATNumber::class),
            new ClassMap('UserGetCompanyVATNumberResponse', Type\UserGetCompanyVATNumberResponse::class),
            new ClassMap('UserGetCustomerAccount', Type\UserGetCustomerAccount::class),
            new ClassMap('UserGetCustomerAccountResponse', Type\UserGetCustomerAccountResponse::class),
            new ClassMap('UserGetEmail', Type\UserGetEmail::class),
            new ClassMap('UserGetEmailResponse', Type\UserGetEmailResponse::class),
            new ClassMap('UserGetBirthDate', Type\UserGetBirthDate::class),
            new ClassMap('UserGetBirthDateResponse', Type\UserGetBirthDateResponse::class),
            new ClassMap('UserGetFiscalCode', Type\UserGetFiscalCode::class),
            new ClassMap('UserGetFiscalCodeResponse', Type\UserGetFiscalCodeResponse::class),
            new ClassMap('UserGetFisrtName', Type\UserGetFisrtName::class),
            new ClassMap('UserGetFisrtNameResponse', Type\UserGetFisrtNameResponse::class),
            new ClassMap('UserGetLanguage', Type\UserGetLanguage::class),
            new ClassMap('UserGetLanguageResponse', Type\UserGetLanguageResponse::class),
            new ClassMap('UserGetLastName', Type\UserGetLastName::class),
            new ClassMap('UserGetLastNameResponse', Type\UserGetLastNameResponse::class),
            new ClassMap('UserGetPassword', Type\UserGetPassword::class),
            new ClassMap('UserGetPasswordResponse', Type\UserGetPasswordResponse::class),
            new ClassMap('UserGetPriceIndex', Type\UserGetPriceIndex::class),
            new ClassMap('UserGetPriceIndexResponse', Type\UserGetPriceIndexResponse::class),
            new ClassMap('UserGetDiscount', Type\UserGetDiscount::class),
            new ClassMap('UserGetDiscountResponse', Type\UserGetDiscountResponse::class),
            new ClassMap('UserGetDiscountGridCode', Type\UserGetDiscountGridCode::class),
            new ClassMap('UserGetDiscountGridCodeResponse', Type\UserGetDiscountGridCodeResponse::class),
            new ClassMap('UserGetSubscribeToNewletters', Type\UserGetSubscribeToNewletters::class),
            new ClassMap('UserGetSubscribeToNewlettersResponse', Type\UserGetSubscribeToNewlettersResponse::class),
            new ClassMap('UserGetSalesCodeRep', Type\UserGetSalesCodeRep::class),
            new ClassMap('UserGetSalesCodeRepResponse', Type\UserGetSalesCodeRepResponse::class),
            new ClassMap('UserGetShippingAddress', Type\UserGetShippingAddress::class),
            new ClassMap('UserGetShippingAddressResponse', Type\UserGetShippingAddressResponse::class),
            new ClassMap('UserGetShippingAddressLines', Type\UserGetShippingAddressLines::class),
            new ClassMap('UserGetShippingAddressLinesResponse', Type\UserGetShippingAddressLinesResponse::class),
            new ClassMap('UserGetList', Type\UserGetList::class),
            new ClassMap('UserListEntity', Type\UserListEntity::class),
            new ClassMap('PaginationEntity', Type\PaginationEntity::class),
            new ClassMap('ArrayOfUserIdEntity', Type\ArrayOfUserIdEntity::class),
            new ClassMap('UserGetListResponse', Type\UserGetListResponse::class),
            new ClassMap('SoapDataResultServiceOfUserListDataUserListEntity', Type\SoapDataResultServiceOfUserListDataUserListEntity::class),
            new ClassMap('UserListData', Type\UserListData::class),
        ]);
    }


}

