language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - composer self-update --no-interaction

install:
    - composer install --prefer-dist --no-interaction

script:
    - bin/phpspec run --no-interaction

notifications:
    email: false
