Heavymind\Oxatis\ApiClient\Type\ProductPackagingEntityType:
    properties:
        defaultPackagingName:
            expose: true
            access_type: public_method
            serialized_name: DefaultPackagingName
            accessor:
                getter: getDefaultPackagingName
                setter: setDefaultPackagingName
            type: string
        productPackagingItem:
            expose: true
            access_type: public_method
            serialized_name: ProductPackagingItem
            accessor:
                getter: getProductPackagingItem
                setter: setProductPackagingItem
            xml_list:
                inline: true
                entry_name: ProductPackagingItem
            type: array<Heavymind\Oxatis\ApiClient\Type\ProductPackagingItemEntityType>
