Heavymind\Oxatis\ApiClient\Type\ProductAttributeTextEntityType:
    properties:
        text:
            expose: true
            access_type: public_method
            serialized_name: Text
            accessor:
                getter: getText
                setter: setText
            type: string
        type:
            expose: true
            access_type: public_method
            serialized_name: Type
            accessor:
                getter: getType
                setter: setType
            type: string
