Heavymind\Oxatis\ApiClient\Type\ProductBundleEntityType:
    properties:
        bundledItems:
            expose: true
            access_type: public_method
            serialized_name: BundledItems
            accessor:
                getter: getBundledItems
                setter: setBundledItems
            type: array<Heavymind\Oxatis\ApiClient\Type\ProductBundledItemEntityType>
            xml_list:
                inline: false
                entry_name: BundledItem
                skip_when_empty: true
