Heavymind\Oxatis\ApiClient\Type\ProductPackagingItemEntityType:
    properties:
        quantity:
            expose: true
            access_type: public_method
            serialized_name: Quantity
            accessor:
                getter: getQuantity
                setter: setQuantity
            type: int
