Heavymind\Oxatis\ApiClient\Type\ProductPackagingItemBaseEntityType:
    properties:
        itemSKU:
            expose: true
            access_type: public_method
            serialized_name: ItemSKU
            accessor:
                getter: getItemSKU
                setter: setItemSKU
            type: string
        name:
            expose: true
            access_type: public_method
            serialized_name: Name
            accessor:
                getter: getName
                setter: setName
            type: string
        price:
            expose: true
            access_type: public_method
            serialized_name: Price
            accessor:
                getter: getPrice
                setter: setPrice
            type: float
        optional:
            expose: true
            access_type: public_method
            serialized_name: Optional
            accessor:
                getter: getOptional
                setter: setOptional
            type: bool
