Heavymind\Oxatis\ApiClient\Type\ProductEntityType:
    properties:
        quantityInStock:
            expose: true
            access_type: public_method
            serialized_name: QuantityInStock
            accessor:
                getter: getQuantityInStock
                setter: setQuantityInStock
            type: Heavymind\Oxatis\ApiClient\Type\QuantityEntityType
        quantityReorder:
            expose: true
            access_type: public_method
            serialized_name: QuantityReorder
            accessor:
                getter: getQuantityReorder
                setter: setQuantityReorder
            type: Heavymind\Oxatis\ApiClient\Type\QuantityEntityType
        unitsForSale:
            expose: true
            access_type: public_method
            serialized_name: UnitsForSale
            accessor:
                getter: getUnitsForSale
                setter: setUnitsForSale
            type: int
        unitsForSale1:
            expose: true
            access_type: public_method
            serialized_name: UnitsForSale1
            accessor:
                getter: getUnitsForSale1
                setter: setUnitsForSale1
            type: int
        unitsForSale2:
            expose: true
            access_type: public_method
            serialized_name: UnitsForSale2
            accessor:
                getter: getUnitsForSale2
                setter: setUnitsForSale2
            type: int
        unitsForSale3:
            expose: true
            access_type: public_method
            serialized_name: UnitsForSale3
            accessor:
                getter: getUnitsForSale3
                setter: setUnitsForSale3
            type: int
        unitsForSale4:
            expose: true
            access_type: public_method
            serialized_name: UnitsForSale4
            accessor:
                getter: getUnitsForSale4
                setter: setUnitsForSale4
            type: int
        unitsForSale5:
            expose: true
            access_type: public_method
            serialized_name: UnitsForSale5
            accessor:
                getter: getUnitsForSale5
                setter: setUnitsForSale5
            type: int
        unitsForSale6:
            expose: true
            access_type: public_method
            serialized_name: UnitsForSale6
            accessor:
                getter: getUnitsForSale6
                setter: setUnitsForSale6
            type: int
        unitsForSale7:
            expose: true
            access_type: public_method
            serialized_name: UnitsForSale7
            accessor:
                getter: getUnitsForSale7
                setter: setUnitsForSale7
            type: int
        unitsForSale8:
            expose: true
            access_type: public_method
            serialized_name: UnitsForSale8
            accessor:
                getter: getUnitsForSale8
                setter: setUnitsForSale8
            type: int
        unitsForSale9:
            expose: true
            access_type: public_method
            serialized_name: UnitsForSale9
            accessor:
                getter: getUnitsForSale9
                setter: setUnitsForSale9
            type: int
