Heavymind\Oxatis\ApiClient\Type\ProductRemoteURLEntityType:
    properties:
        url:
            expose: true
            access_type: public_method
            serialized_name: Url
            accessor:
                getter: getUrl
                setter: setUrl
            type: string
