Heavymind\Oxatis\ApiClient\Type\ProductPackagingPerPriceEntityType:
    properties:
        priceIndex:
            expose: true
            access_type: public_method
            serialized_name: PriceIndex
            accessor:
                getter: getPriceIndex
                setter: setPriceIndex
            type: int
