Heavymind\Oxatis\ApiClient\Type\ProductCategoryEntityType:
    properties:
        parentCategory:
            expose: true
            access_type: public_method
            serialized_name: ParentCategory
            accessor:
                getter: getParentCategory
                setter: setParentCategory
            type: Heavymind\Oxatis\ApiClient\Type\CategoryEntityType
        header:
            expose: true
            access_type: public_method
            serialized_name: Header
            accessor:
                getter: getHeader
                setter: setHeader
            type: string
        metaKeywords:
            expose: true
            access_type: public_method
            serialized_name: MetaKeywords
            accessor:
                getter: getMetaKeywords
                setter: setMetaKeywords
            type: string
        metaDescription:
            expose: true
            access_type: public_method
            serialized_name: MetaDescription
            accessor:
                getter: getMetaDescription
                setter: setMetaDescription
            type: string
        metaTitle:
            expose: true
            access_type: public_method
            serialized_name: MetaTitle
            accessor:
                getter: getMetaTitle
                setter: setMetaTitle
            type: string
        imgFileName:
            expose: true
            access_type: public_method
            serialized_name: ImgFileName
            accessor:
                getter: getImgFileName
                setter: setImgFileName
            type: string
        description:
            expose: true
            access_type: public_method
            serialized_name: Description
            accessor:
                getter: getDescription
                setter: setDescription
            type: string
