Heavymind\Oxatis\ApiClient\Type\ProductWebBlockEntityType:
    properties:
        descriptionWebBlock:
            expose: true
            access_type: public_method
            serialized_name: DescriptionWebBlock
            accessor:
                getter: getDescriptionWebBlock
                setter: setDescriptionWebBlock
            type: string
        longDescriptionWebBlock:
            expose: true
            access_type: public_method
            serialized_name: LongDescriptionWebBlock
            accessor:
                getter: getLongDescriptionWebBlock
                setter: setLongDescriptionWebBlock
            type: string
